//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int ID { get; set; }
        public string cust_id { get; set; }
        public int product_id { get; set; }
        public int amount { get; set; }
        public bool IsInCart { get; set; }
    
        public virtual product product { get; set; }
    }
}
