//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class cust_info
    {
        public int ID { get; set; }
        public string cust_fname { get; set; }
        public string cust_lname { get; set; }
        public string cust_address { get; set; }
        public string cust_email { get; set; }
        public decimal cust_contact { get; set; }
    }
}
